### ISSUE TITLE
Embedding a ListView with RecyclerViewBackedScrollView enabled leads to crashes.

### ISSUE THREAD

**Issue by rborn** [aybadb/react-native-android-kit#19]
A ListView that has RecyclerViewBackedScrollView enabled will lead to 2 issues:
- the list won't render initially (after a change of the state will do though)
- as soon as you wanna scroll or even earlier the app will crash with the next error

```
java.lang.AbstractMethodError: abstract method not implemented
at android.support.v7.widget.RecyclerView$ItemAnimator.animatePersistence(RecyclerView.java)
at android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:450)
at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:243)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3098)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
at android.view.View.layout(View.java:14841)
```

ENV:
react-native-cli: 1.2.0
react-native: 0.37.0

Any idea? 
Thank you.

**Comment by rborn** [comment]
It looks like RecyclerViewBackedScrollView is getting deprecated, closing.
